spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true
  

  rabbitmq:
    host: 192.168.92.132
    port: 5672
    username: admin
    password: admin
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream